version: "3"

networks:
  d.net:
    driver: bridge

services:
###########
 # service php / apache utilisant un vhost dont le nom est celui de la machine hôte
 #
 #  le service sera accessible à https://docketu.iutnc.univ-lorraine.fr:14001
###########

  api.events:
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=docketu.iutnc.univ-lorraine.local
      - VHOST_DOCROOT=/var/www/api
#      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
#      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
    ports:
      - "14000:80"
      - "14001:443"
    volumes:
      - ./backend1/public:/var/www/api
      - ./backend1/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - d.net
    links:
      - mysql:db

###########
# service php / apache utilisant le vhost par défaut
#
#  le service sera accessible à https://docketu.iutnc.univ-lorraine.fr:19143
###########
  # back2:
  #   image: canals/php:latest
  #   environment:
  #     - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
  #     - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
  #   ports:
  #   - "14002:80"
  #   - "14003:443"
  #   volumes:
  #   - ./backend2/public:/var/www/html
  #   - ./backend2/src:/var/www/src
  #   working_dir: /var/www/src
  #   networks:
  #   - d.net
  #   links:
  #   - mysql:db


#############################
# mysql + phpmyadmin
#############################
  mysql:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_USER=events
      - MYSQL_PASSWORD=events
      - MYSQL_DATABASE=events
    volumes :
      - ./backend1/sql:/var/sql
    networks:
      - d.net

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "14999:80"
    links:
      - mysql:db
    networks:
      - d.net

  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - api.events:docketu.iutnc.univ-lorraine.local
    networks:
      - d.net
    environment:
      - DOMAIN=docketu.iutnc.univ-lorraine.local
      - PORT=14000
    

################################################
# mongodb & mongo-express
###############################################
  # mongo:
  #   image: mongo:latest
  #   volumes:
  #   - ./backend2/data:/var/data
  #   working_dir: /var/data
  #   networks:
  #   - d.net


  # mongo-express:
  #   image: mongo-express:latest
  #   networks:
  #   - d.net
  #   ports:
  #   - "19781:8081"
  #   links:
  #   - mongo:mongo
